steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-docker.pkg.dev/$PROJECT_ID/workshop-repo/campus-vibe-board:$COMMIT_SHA
      - ./app

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - campus-vibe-board
      - --image=us-docker.pkg.dev/$PROJECT_ID/workshop-repo/campus-vibe-board:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated

substitutions:
  _REGION: us-central1

images:
  - us-docker.pkg.dev/$PROJECT_ID/workshop-repo/campus-vibe-board:$COMMIT_SHA
